### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by zecmo** [Arxareon/MovementSpeed#12] opened 2024-04-13 08:36 UTC
First, want to say I really like this AddOn. It's simplicity in use and design was exactly what I was looking for.

On to the bug:
I noticed my AddOn Memory footprint was perpetually increasing.
Disabled all my AddOns, tested each one by one, and discovered it's MovementSpeed.

If you are able to look into this, I would be willing to assist with testing, debugging, etc.

"For the Horde!"

**Comment by zecmo** [comment] 2024-04-13 09:38
Upon further investigation, adjusting some settings...

In Settings, under Speed Display -> Travel Speed, when I toggle off Enable Functionality the memory leak is greatly reduced. By about a factor of 10. 
With it toggled on, about 10kb is added every update. When off, it's only about 1kb.

Also noticed, when the setting has been on for a bit, then turned off, within a few minutes the AddOn's memory is reduced. [In my test I saw a 10MB+ footprint reduce to under 1MB]

Hopefully this helps.

**Comment by Arxareon** [comment] 2024-04-13 12:52
Yes, thanks forr the report!

I'm aware of the issue, it's caused by the throttled update frequency (Travel Speed uses Throttle by default). _**Could you perhaps confirm that?**_
It's working with Blizzard's ticking timers in the background. It's a nice way to reduce computing time as normally, speed would be recalculated and updated every frame. But, it's not much of a difference and RAM usage is proportionally more.
The other use for throttled updates is letting the speed text be more readable. As the Travel Speed numbers change a lot from moment to moment, having it update every frame makes it difficult to follow and read at a glance. There are ways to fix this without resorting to timers, I'll be working on ways to get around this.

I'm working on a huge update at the moment (have been for a while now but I have limited time) that I need to get out the door as soon as possible, this will probably have to come after that. If I find a simple solution that works (have one in mind), I will probably include it in the next update. There are just a couple of kinks to iron out,, but unfortunately I can't give a solid ETA.

I'll try my best to release it soon!

**Comment by zecmo** [comment] 2024-04-14 07:25
> (Travel Speed uses Throttle by default). Could you perhaps confirm that?

If I understand your request correctly, yes, for me under the Travel Speed, all 3 checkboxes were checked by default.
**Enable Functionality**, **Throttle Updates**, and **As a Replacement**

But you could mean, which I did test, if I check **Enable Functionality** and uncheck **Throttle Updates**, the memory footprint does increase steadily by about 1kb per updates. Then will eventually dump some memory which keeps it under a certain amount. Seems to be 500kb and under.

Does seem to be overall slowly increasing, but I only reviewed for about 7-8 min.

Hope this helps.

**Comment by Arxareon** [comment] 2024-07-22 02:14
I replaced the ticking timer solution so this should be resolved in the next update.
Addon version `3.0 Test A` (currently in testing) does not yet have this fix, the next release will.

**Closed as completed by Arxareon** 2024-07-22 02:14 UTC
Labels: Resolved in the next update, Improvement
